openapi: 3.0.3
info:
  title: Cittadino API
  version: 1.0.0
  description: API per ottenere informazioni richieste di un cittadino a partire dal codice fiscale

paths:
  /cittadino/{codiceFiscale}:
    get:
      tags:
        - Cittadino
      summary: Ottieni data di nascita ed età del cittadino dato il codice fiscale
      operationId: getCittadinoByCodiceFiscale
      parameters:
        - name: codiceFiscale
          in: path
          required: true
          description: Codice fiscale del cittadino
          schema:
            type: string
            example: RSSMRA97A01H501C
      responses:
        '200':
          description: Informazioni trovate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CittadinoDto'
        '404':
          description: Cittadino non trovato

components:
  schemas:
    CittadinoDto:
      type: object
      properties:
        birthDate:
          type: string
          format: date
          example: 1997-01-01
        age:
          type: integer
          example: 28
